version: '3.9'

services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "startup_team_bd"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - "5432:5432"